Add privacy policy page
nhs-digital-gp-it-futures/public-browse pull request #463
Opened 2021-05-18 17:08 UTC by NickNewlands

Story: AB#13179
Ticket: AB#14634

2021-05-18 17:09 UTC, NickNewlands commented
This requires https://github.com/nhs-digital-gp-it-futures/buying-catalogue-components/pull/312/commits/520a927bddad154e6e88fc262bc657973d53af53

The tests will fail until I have merged that and updated the BCC package here but it's good to be reviewed.

2021-05-19 08:47 UTC, bjss-chris requested changes
Looks good just needs one EOF file fix.

2021-05-19 08:47 UTC, bjss-chris commented on app/pages/privacy-policy/template.njk
> +{% endblock %}
Should end with a trailing new line.

2021-05-19 15:16 UTC, bjss-chris approved these changes

2021-05-19 15:34 UTC, merged